### PR TITLE
Fix all the code

### PR DESCRIPTION
**Pull request by Gowixx**
Fix all of the aids code, how did you miss all of this lmfao

### CODE REVIEW

**Comment by josephworks** [comment]
You forgot to add the methods, please fix and resubmit in scala.

**Comment by Gowixx** [comment]
method no need, i good like this

**Comment by josephworks** [comment]
I dont think that. Method need yes yes? Yes.

**Comment by Gowixx** [comment]
I fixed it

**Comment by josephworks** [comment]
Returning yanchop causes a NullPointerException. Please add the missing yanchop.

**Comment by josephworks** [comment]
fix the issue on line 19

**Comment by Gowixx** [comment]
youre so mean, im blocking you !!!!!!!! 
die!!!!!!!!!!!!!!!!

**Comment by josephworks** [comment]
This is so sad.

**Pull request closed without merging**
